# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac37c03bd68c4d7af73974e2060961aa734a05085da95ee6b52fd07bb94979d6e60fef843fe056313f33c7e67e67bebe39161ae0583aa527d9bb403ef641dab4

test:
  secret_key_base: 3e0cfb9726a541218494b5f19b16c63368b0f0586f72eff171781fa5cfacea1ce83faa19f94231539dba85914cca1c5d6d39e08836ab6cdeadc09c9c12590d6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
